<<<<<<< HEAD
# ------------------------------
# In the streamlit app this will be set in the app settings - secrets
# ------------------------------
=======
>>>>>>> a9b519cc00d08f0dc63bf76118a3a11ad438bf75
AUTH_USERNAME = "DSP_ENG"
AUTH_PASSWORD = "DSP_ENG_2026"
